inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  CountAsOne: [array, heredoc, hash] # method_call
  Max: 200
Metrics/MethodLength:
  Max: 20
Gemspec/AddRuntimeDependency:
  Enabled: false
